// Author: Gabriel Armas

using System;
using System.Collections.Generic;
using Meta.XR.Samples;
using PassthroughCameraSamples.StartScene;
using UnityEngine;
using UnityEngine.SceneManagement;
using OVRSimpleJSON;

namespace PassthroughCameraSamples.SelectProject
{
    /// <summary>
    /// Handles project suggestions generated by OpenAI.
    /// CENTER panel: list of suggested project titles.
    /// RIGHT panel: details + components (paginated).
    /// </summary>
    public class ProjectSuggestionsScreen : MonoBehaviour
    {
        [Header("Dependencies")]
        [SerializeField] private ArduinoImageOpenAIConnector openAIConnector;
        [SerializeField] private RollingAnimationLoader rollingLoader;

        // UI builder reference
        private DebugUIBuilder uiBuilder;

        // Data from OpenAI
        private readonly List<JSONNode> projectList = new List<JSONNode>();

        // Pagination for RIGHT pane
        private int componentPage = 0;
        private const int componentPageSize = 3;

        private JSONArray currentComponents;
        private string currentTitle;
        private string currentDescription;


        // ---------------------------------------------------------------------
        // LIFECYCLE
        // ---------------------------------------------------------------------

        private void Start()
        {
            uiBuilder = DebugUIBuilder.Instance;

            // Listen for OpenAI response BEFORE requesting
            openAIConnector.onJsonReceived.AddListener(OnProjectsJsonReceived);

            // Request project ideas
            string inventoryString = StaticClass.generateCompoundStringOfComponents();
            openAIConnector.GenerateProjects(inventoryString);

            // Display loading animation
            ShowLoadingUI();
        }


        // ---------------------------------------------------------------------
        // INITIAL LOADING UI
        // ---------------------------------------------------------------------

        /// <summary>
        /// Shows "Generating Projects..." loading screen.
        /// </summary>
        private void ShowLoadingUI()
        {
            uiBuilder.Clear(DebugUIBuilder.DEBUG_PANE_CENTER);

            rollingLoader.LoadRollingAnimation(DebugUIBuilder.DEBUG_PANE_CENTER);

            _ = uiBuilder.AddLabel(
                "Generating Projects...",
                DebugUIBuilder.DEBUG_PANE_CENTER,
                40
            );

            uiBuilder.Show();
        }


        // ---------------------------------------------------------------------
        // JSON HANDLING
        // ---------------------------------------------------------------------

        /// <summary>
        /// Called when OpenAI returns project suggestions.
        /// Parses JSON and generates the list of buttons.
        /// </summary>
        private void OnProjectsJsonReceived(string json)
        {
            Debug.Log("Received project suggestions JSON.");

            try
            {
                JSONNode root = JSON.Parse(json);
                string rawContent = root["choices"][0]["message"]["content"];

                // Remove Markdown formatting if present
                string cleaned = rawContent
                    .Replace("```json", "")
                    .Replace("```", "")
                    .Trim();

                // Parse final JSON payload
                JSONNode result = JSON.Parse(cleaned);
                JSONArray projArray = result["projects"].AsArray;

                projectList.Clear();
                foreach (var p in projArray)
                    projectList.Add(p.Value);

                ShowProjectButtons();
            }
            catch (Exception e)
            {
                Debug.LogError("Error parsing project suggestions JSON: " + e.Message);
            }
        }


        // ---------------------------------------------------------------------
        // CENTER PANEL — PROJECT BUTTONS
        // ---------------------------------------------------------------------

        /// <summary>
        /// Displays a button for each suggested project.
        /// Clicking a project loads its component details in the RIGHT pane.
        /// </summary>
        private void ShowProjectButtons()
        {
            uiBuilder.Clear(DebugUIBuilder.DEBUG_PANE_CENTER);

            // Back button
            uiBuilder.LoadComponentImage(
                uiBuilder,
                "icons/back-btn.png",
                DebugUIBuilder.DEBUG_PANE_CENTER,
                () => LoadScene(1)
            );

            _ = uiBuilder.AddLabel("Project Suggestions",
                DebugUIBuilder.DEBUG_PANE_CENTER,
                48
            );

            for (int i = 0; i < projectList.Count; i++)
            {
                var project = projectList[i];

                string title = project["title"];
                string description = project["description"];
                JSONArray components = project["components"].AsArray;

                // Shorten long titles
                string preview = title.Length > 27 ? title.Substring(0, 27) + "..." : title;

                _ = uiBuilder.AddButton(
                    $"{i + 1}. {preview}",
                    () => LoadSidePanel(title, description, components),
                    -1,
                    DebugUIBuilder.DEBUG_PANE_CENTER
                );

                _ = uiBuilder.AddDivider(DebugUIBuilder.DEBUG_PANE_CENTER);
            }

            uiBuilder.Show();
        }


        // ---------------------------------------------------------------------
        // RIGHT PANEL — COMPONENT DETAILS + PAGINATION
        // ---------------------------------------------------------------------

        /// <summary>
        /// Loads the right-side panel with the details of a selected project.
        /// </summary>
        private void LoadSidePanel(string title, string description, JSONArray components)
        {
            currentTitle = title;
            currentDescription = description;
            currentComponents = components;

            componentPage = 0;

            ShowComponentPage();
        }

        /// <summary>
        /// Shows the paginated list of components required for the selected project.
        /// </summary>
        private void ShowComponentPage()
        {
            uiBuilder.Clear(DebugUIBuilder.DEBUG_PANE_RIGHT);

            // TITLE + DESCRIPTION
            _ = uiBuilder.AddParagraph(currentTitle, DebugUIBuilder.DEBUG_PANE_RIGHT, 40);
            _ = uiBuilder.AddParagraph(currentDescription, DebugUIBuilder.DEBUG_PANE_RIGHT, 20);

            // SELECT PROJECT (loads instructions)
            _ = uiBuilder.AddButton("Select Project", () =>
            {
                StaticClass.Reset();
                StaticClass.projectTitle = currentTitle;
                StaticClass.projectDescription = currentDescription;

                // Transfer components to inventory
                for (int i = 0; i < currentComponents.Count; i++)
                {
                    string item = currentComponents[i]["item"];
                    int qty = currentComponents[i]["quantity"];
                    StaticClass.AddComponentQuantity(item, qty);
                }

                LoadScene(9);
            },
            -1,
            DebugUIBuilder.DEBUG_PANE_RIGHT);

            _ = uiBuilder.AddDivider(DebugUIBuilder.DEBUG_PANE_RIGHT);


            // ----------------------
            // PAGINATION MATH
            // ----------------------
            int total = currentComponents.Count;
            int totalPages = Mathf.CeilToInt(total / (float)componentPageSize);

            int start = componentPage * componentPageSize;
            int end = Mathf.Min(start + componentPageSize, total);


            // Page Indicator
            if (total > componentPageSize)
            {
                _ = uiBuilder.AddLabel(
                    $"Page {componentPage + 1} / {totalPages}",
                    DebugUIBuilder.DEBUG_PANE_RIGHT,
                    30
                );
                _ = uiBuilder.AddDivider(DebugUIBuilder.DEBUG_PANE_RIGHT);
            }


            // ----------------------
            // COMPONENTS FOR PAGE
            // ----------------------
            for (int i = start; i < end; i++)
            {
                JSONNode comp = currentComponents[i];

                string item = comp["item"];
                int qty = comp["quantity"];

                // Thumbnail
                uiBuilder.LoadComponentImage(
                    uiBuilder,
                    $"2dmod/{item}.jpg",
                    DebugUIBuilder.DEBUG_PANE_RIGHT,
                    () => { }
                );

                // Text
                _ = uiBuilder.AddLabel(
                    $"{item} (x{qty})",
                    DebugUIBuilder.DEBUG_PANE_RIGHT,
                    22
                );

                _ = uiBuilder.AddDivider(DebugUIBuilder.DEBUG_PANE_RIGHT);
            }


            // ----------------------
            // PAGINATION BUTTONS
            // ----------------------
            if (componentPage > 0)
            {
                _ = uiBuilder.AddButton(
                    "← Previous Page",
                    () =>
                    {
                        componentPage--;
                        ShowComponentPage();
                    },
                    -1,
                    DebugUIBuilder.DEBUG_PANE_RIGHT
                );
            }

            if ((componentPage + 1) * componentPageSize < total)
            {
                _ = uiBuilder.AddButton(
                    "Next Page →",
                    () =>
                    {
                        componentPage++;
                        ShowComponentPage();
                    },
                    -1,
                    DebugUIBuilder.DEBUG_PANE_RIGHT
                );
            }

            uiBuilder.Show();
        }


        // ---------------------------------------------------------------------
        // SCENE LOADING
        // ---------------------------------------------------------------------

        private void LoadScene(int idx)
        {
            DebugUIBuilder.Instance.Hide();
            SceneManager.LoadScene(idx);
        }
    }
}
